services:
  mysql:
    image: mysql:8.0
    container_name: mysql-veterinaria
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: veterinaria
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - red-vet

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    restart: always
    networks:
      - red-vet

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./:/workspace
    restart: always
    networks:
      - red-vet

volumes:
  mysql_data:
  jenkins_home:

networks:
  red-vet:
    driver: bridge